---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get running instances
      ec2_instance_facts:
        region: "{{ aws_region }}"
        filters:
          instance-state-name: ["running", "shutting-down", "stopping", "stopped"]
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: import ssh key
      ec2_key:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ aws_ec2_key_name }}"
        key_material: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        region: "{{ aws_region }}"
        state: "{{ aws_ec2_resource_state }}"
      tags: ssh

    - name: Create the instances
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ aws_ec2_key_name }}"
        instance_type: "{{ aws_ec2_instance_type }}"
        image: "{{ aws_ec2_ami }}"
        state: "{{ aws_ec2_resource_state }}"
        wait: yes
        region: "{{ aws_region }}"
        group: "{{ aws_security_group_name }}"
        count: "{{ aws_ec2_instance_count }}"
        vpc_subnet_id: "{{ ajsubnet.subnet.id }}"
        assign_public_ip: yes
      when: ec2.instances | length==0
      tags: ec2
