---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
  - name: Get running instances
    ec2_instance_facts:
      region: "{{ aws_region }}"
      filters:
        instance-state-name: running
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    register: ec2

  - name: terminate instances
    ec2:
      state: 'absent'
      instance_ids: "{{ item.instance_id }}"
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    with_items: "{{ ec2.instances }}"
    tags: terminate
