---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    packages: [ bind-utils, net-tools, vim, wget ]
    yuminstall: [ epel-release, nginx-1.16.0 ]
  tasks:
    - name: install common tools
      become: true
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: Install all yum packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ yuminstall }}"

    - name: upgrade all packages
      become: true
      package:
        name: '*'
        state: latest

    - name: Generate index homepage from template
      become: true
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: start nginx
      become: true
      service:
        name: nginx
        state: started
