---
- import_playbook: users.yml

- hosts: webservers
  roles:
    - webserver

- hosts: loadbalancers
  become: yes
  tasks:
    - name: Update ALL
      yum:
        name: "*"
        state: latest
  roles:
    - geerlingguy.haproxy
