---
- name: create group nginx-exp
  become: true
  group:
    name: "{{ nginx_group }}"
    state: present
- name: create group nginx-exp
  become: true
  user:
    name: "{{ nginx_user }}"
    state: present
    group: nginx-exp

- name: Create prometheus directory
  become: true
  file:
    path: /prometheus
    state: directory
    mode: '1777'

- name: Download prometheus Conf
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /prometheus/
    mode: '0777'

- name: Unarchive a file that is already on the remote machine
  become: true
  unarchive:
    src: /prometheus/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true

- name: Template a file to /etc/files.conf
  become: true
  template:
    src: nginx-exporter.j2
    dest: /etc/systemd/system/
    mode: '0644'
