---
- hosts: all
  vars:
    user: [ajones, nsmeds]
  tasks:
    - name: Create user
      become: true
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        group: wheel
      loop: "{{ user }}"

    - name: Change Perm on my Root folder
      become: true
      file:
        path: /home/{{ item }}
        state: directory
        mode: 0750
      loop: "{{ user }}"

    - name: Set authorized pub key
      become: true
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '{{ item }}.pub') }}"
      loop: "{{ user }}"

    - name: Edit Sudoers Files with Users
      become: true
      lineinfile:
        path: /etc/sudoers
        state: present
        mode: 0440
        line: '"{{ item }}" ALL=(root) NOPASSWD: ALL'
      loop: "{{ user }}"
