# -*- mode: ruby -*-
# vi: set ft=ruby :

# Here we create the variable `nodes`, where we define each server with its
# hostname and IP address.
nodes = [
  { :hostname => 'monitor1.test',    :ip => '10.100.0.50' },
  { :hostname => 'monitor2.test',    :ip => '10.100.0.51' },
  { :hostname => 'monitor3.test',    :ip => '10.100.0.52' },
  { :hostname => 'prometheus1.test', :ip => '10.100.0.40' },
  { :hostname => 'prometheus2.test', :ip => '10.100.0.41' },
  { :hostname => 'alertmgr1.test',   :ip => '10.100.0.30' },
  { :hostname => 'alertmgr2.test',   :ip => '10.100.0.31' }
]

HOSTNAME = "AJWEBSERVER"
# Declare configuration version 2. See
# https://www.vagrantup.com/docs/vagrantfile/version.html.
Vagrant.configure("2") do |config|

  # Vagrant boxes allow anyone to package their environment into an image and
  # share it with others. See https://app.vagrantup.com/boxes/search.
  config.vm.box = "centos/7"

  config.vm.hostname = HOSTNAME
  # config.vm.network "forwarded_port", guest: 22, host: 50022
  # config.vm.network "forwarded_port", guest: 80, host: 50080
  # By default, Vagrant will share your project directory to `/vagrant` inside
  # the virtual machine. See https://www.vagrantup.com/docs/synced-folders/.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # Here we loop through the variable `nodes`, deploying and provisioning each
  # of our servers.
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "private_network", ip: node[:ip]
        #virtualbox__intnet: "clusternet"

      # Vagrant supports a number of provisioners. Using the Ansible
      # provisioner, we can tell Vagrant to automatically run our playbooks
      # after a virtual machine is deployed.
      #
      # See https://www.vagrantup.com/docs/provisioning/ansible.html.
      nodeconfig.vm.provision :ansible do |ansible|
        ansible.playbook = "cluster.yml"
        ansible.inventory_path = "inventory/development"
      end
    end
  end
end
