---
- name: get nginx rpmkey
  become: true
  rpm_key:
    key: "{{ nginx_signing_key }}"

- name: add nginx repository
  become: true
  yum_repository:
    name: nginx
    baseurl: "{{ nginx_base_repository }}"
    description: nginx repository
    enabled: true
    gpgcheck: true

- name: install nginx
  become: true
  package:
    name: nginx
    state: present

- name: Turning on Substatus
  become: true
  copy:
    content: |
        server {
            listen       80;
            server_name  localhost;

            #charset koi8-r;
            #access_log  /var/log/nginx/host.access.log  main;

            location / {
               root   /usr/share/nginx/html;
               index  index.html index.htm;
            }

            location /nginx_status {
                stub_status on;
               allow 127.0.0.1;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    dest: /etc/nginx/conf.d/default.conf

- name: override default home page
  become: true
  copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>Hello world.</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>body {font: normal 18px Arial; margin: 4em;}</style>
      </head>
      <body>
        <p>
          YAML supports multi-line blocks using specific indicators.<br />
          Read more at
          <a href="https://yaml-multiline.info">YAML-multiline.info</a>.
        </p>
      </body>
      </html>
    dest: /usr/share/nginx/html/index.html

- name: start / restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- include: exporter.yml

- name: Check that a page returns a status 200 and fail if not
  uri:
    url: http://localhost:80/
    method: GET
    return_content: yes
  register: site
  failed_when: site.status != 200

- name: Check and Fail if 9113/metrics does not return nginx_up 1
  uri:
    url: http://localhost:9113/metrics
    method: GET
    return_content: yes
  register: this
  failed_when: "'nginx_up 1' not in this.content"
